(function(){
const lugares=construirIndiceLugares(),stats=estatisticasAcervo(),obraPorId=new Map(OBRAS.map(o=>[o.id,o]));
const statsEl=document.getElementById('atlas-stats');if(statsEl)statsEl.innerHTML=`<span><strong>${stats.obras}</strong> obras</span><span><strong>${stats.autores}</strong> autores</span><span><strong>${stats.lugaresUnicos}</strong> lugares</span><span><strong>${stats.lugaresComCoordenadas}</strong> no mapa</span>${stats.ocorrenciasAuditadas?`<span><strong>${stats.ocorrenciasAuditadas}</strong> ocorrências auditadas</span>`:''}`;
const map=L.map('atlas-mapa',{scrollWheelZoom:false}).setView([-14.2,-51.9],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap',maxZoom:17}).addTo(map);let grupo=L.markerClusterGroup({maxClusterRadius:50});map.addLayer(grupo);const marcadorPorId={};
const leg=document.getElementById('legenda-atlas'),tiposDisponiveis=Object.keys(TIPOS_LUGAR);tiposDisponiveis.forEach(t=>{const c=TIPOS_LUGAR[t],e=document.createElement('div');e.className='legenda-item';e.innerHTML=`<span class="legenda-marca" style="--marca-cor:${c.cor}"></span>${c.rotulo}`;leg.appendChild(e)});const nota=document.createElement('div');nota.className='legenda-item';nota.innerHTML='<span class="legenda-marca tracejado" style="--marca-cor:#57544a"></span>tracejado = localização ilustrativa';leg.appendChild(nota);const pend=document.createElement('div');pend.className='legenda-item';pend.innerHTML='<span class="legenda-marca" style="--marca-cor:#8d8575"></span>sem marcador = geocodificação pendente';leg.appendChild(pend);
const tipoSelect=document.getElementById('filtro-tipo');tiposDisponiveis.forEach(t=>{const opt=document.createElement('option');opt.value=t;opt.textContent=TIPOS_LUGAR[t].rotulo;tipoSelect.appendChild(opt)});const busca=document.getElementById('busca-lugar'),certezaSelect=document.getElementById('filtro-certeza'),lista=document.getElementById('atlas-lista'),detalhe=document.getElementById('atlas-detalhe'),resultados=document.getElementById('atlas-resultados');const inicial=new URLSearchParams(location.search).get('busca');if(inicial)busca.value=inicial;
function filtrar(){const termo=(busca.value||'').trim().toLowerCase(),tipo=tipoSelect.value,certeza=certezaSelect.value;return lugares.filter(l=>{const texto=[l.nome,...(l.aliases||[]),...l.obras.flatMap(o=>[o.titulo,o.autor])].join(' ').toLowerCase(),bateBusca=!termo||texto.includes(termo),bateTipo=!tipo||l.tipos.includes(tipo),bateCerteza=!certeza||l.certezaPrincipal===certeza;return bateBusca&&bateTipo&&bateCerteza})}
function reconstruirMapa(arr){grupo.clearLayers();Object.keys(marcadorPorId).forEach(k=>delete marcadorPorId[k]);arr.filter(l=>l.localizado).forEach(l=>{const c=TIPOS_LUGAR[l.tipoPrincipal]||TIPOS_LUGAR.mencionado,z=CERTEZAS[l.certezaPrincipal]||CERTEZAS.ilustrativo,m=L.circleMarker([l.lat,l.lon],{radius:5+Math.min(l.obras.length,8)*1.6,color:c.cor,weight:2,dashArray:z.tracejado?'3,3':null,fillColor:'#f1ebdd',fillOpacity:.9});m.on('click',()=>mostrarDetalhe(l.id));m.bindTooltip(`${l.nome} · ${l.obras.length} obra${l.obras.length>1?'s':''}`);grupo.addLayer(m);marcadorPorId[l.id]=m})}
function render(){const arr=filtrar(),noMapa=arr.filter(l=>l.localizado).length;lista.innerHTML='';resultados.textContent=`${arr.length} lugar${arr.length===1?'':'es'} · ${noMapa} com coordenadas`;if(!arr.length){lista.innerHTML='<p class="vazio">Nenhum lugar corresponde aos filtros.</p>';detalhe.innerHTML='<p class="atlas-detalhe-vazio">Ajuste a busca ou limpe os filtros para continuar.</p>';reconstruirMapa([]);return}arr.forEach(l=>{const b=document.createElement('button');b.className='atlas-lista-item';b.type='button';b.innerHTML=`<span><span class="atlas-place-name">${l.nome}</span><small>${l.localizado?'no mapa':'geocodificação pendente'}${l.ocorrencias?` · ${l.ocorrencias} ocorrência${l.ocorrencias===1?'':'s'}`:''}</small></span><strong>${l.obras.length}</strong>`;b.onclick=()=>mostrarDetalhe(l.id);lista.appendChild(b)});reconstruirMapa(arr)}
function mostrarDetalhe(id){const l=lugares.find(x=>x.id===id);if(!l)return;const m=marcadorPorId[id];if(m){map.setView([l.lat,l.lon],Math.max(map.getZoom(),6));grupo.zoomToShowLayer(m,()=>m.openTooltip())}const tipos=l.tipos.map(t=>(TIPOS_LUGAR[t]||TIPOS_LUGAR.mencionado).rotulo).join(' · '),certeza=(CERTEZAS[l.certezaPrincipal]||CERTEZAS.ilustrativo).rotulo,movimentos=[...new Set(l.obras.map(o=>obraPorId.get(o.id)?.movimento).filter(Boolean))];detalhe.innerHTML=`<div class="eyebrow">Lugar${l.entity_id?' canônico':''}</div><h3>${l.nome}</h3><div class="atlas-status-row"><span class="badge">${l.localizado?'coordenadas disponíveis':'geocodificação pendente'}</span>${l.ocorrencias?`<span class="badge">${l.ocorrencias} ocorrência${l.ocorrencias===1?'':'s'} auditada${l.ocorrencias===1?'':'s'}</span>`:''}</div><p class="atlas-detalhe-conta">${l.obras.length} obra${l.obras.length>1?'s':''} do acervo passa${l.obras.length>1?'m':''} por este lugar.</p><p class="atlas-detalhe-tipos">${tipos||'sem classificação'} · ${certeza}</p>${movimentos.length?`<p class="atlas-detalhe-meta">Movimentos: ${movimentos.join(' · ')}</p>`:''}${l.aliases?.length?`<p class="atlas-detalhe-meta">Formas registradas: ${l.aliases.join(' · ')}</p>`:''}<ul class="atlas-obras-aqui">${l.obras.map(o=>`<li><a href="obra.html?id=${o.id}"><strong>${o.titulo}</strong><span>${o.autor} · ${o.ano}</span></a></li>`).join('')}</ul>`}
[busca,tipoSelect,certezaSelect].forEach(el=>el.addEventListener(el===busca?'input':'change',render));document.getElementById('limpar-filtros').addEventListener('click',()=>{busca.value='';tipoSelect.value='';certezaSelect.value='';history.replaceState(null,'',location.pathname);render();busca.focus()});render();
})();