(function(){
const lugares=construirIndiceLugares();const stats=estatisticasAcervo();document.getElementById('atlas-stats').innerHTML=`<span><strong>${stats.obras}</strong> obras</span><span><strong>${stats.autores}</strong> autores</span><span><strong>${stats.lugaresUnicos}</strong> lugares únicos</span>`;
const map=L.map('atlas-mapa',{scrollWheelZoom:false}).setView([-14.2,-51.9],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap',maxZoom:17}).addTo(map);const grupo=L.markerClusterGroup({maxClusterRadius:50});const marcadorPorNome={};const tiposUsados=new Set();
lugares.forEach(l=>{const c=TIPOS_LUGAR[l.tipoPrincipal]||TIPOS_LUGAR.mencionado;const z=CERTEZAS[l.certezaPrincipal]||CERTEZAS.ilustrativo;tiposUsados.add(l.tipoPrincipal);const m=L.circleMarker([l.lat,l.lon],{radius:5+Math.min(l.obras.length,8)*1.6,color:c.cor,weight:2,dashArray:z.tracejado?'3,3':null,fillColor:'#f1ebdd',fillOpacity:.9});m.on('click',()=>mostrarDetalhe(l.nome));m.bindTooltip(`${l.nome} · ${l.obras.length} obra${l.obras.length>1?'s':''}`);grupo.addLayer(m);marcadorPorNome[l.nome]=m});map.addLayer(grupo);
const leg=document.getElementById('legenda-atlas');tiposUsados.forEach(t=>{const c=TIPOS_LUGAR[t];const e=document.createElement('div');e.className='legenda-item';e.innerHTML=`<span class="legenda-marca" style="--marca-cor:${c.cor}"></span>${c.rotulo}`;leg.appendChild(e)});const nota=document.createElement('div');nota.className='legenda-item';nota.innerHTML='<span class="legenda-marca tracejado" style="--marca-cor:#57544a"></span>contorno tracejado = localização ilustrativa';leg.appendChild(nota);
const lista=document.getElementById('atlas-lista'),detalhe=document.getElementById('atlas-detalhe');function renderLista(f=''){lista.innerHTML='';const termo=f.trim().toLowerCase();const arr=lugares.filter(l=>l.nome.toLowerCase().includes(termo));if(!arr.length){lista.innerHTML='<p class="vazio">Nenhum lugar encontrado.</p>';return}arr.forEach(l=>{const b=document.createElement('button');b.className='atlas-lista-item';b.type='button';b.innerHTML=`<span>${l.nome}</span><strong>${l.obras.length}</strong>`;b.onclick=()=>mostrarDetalhe(l.nome);lista.appendChild(b)})}
function mostrarDetalhe(nome){const l=lugares.find(x=>x.nome===nome);if(!l)return;const m=marcadorPorNome[nome];if(m){map.setView([l.lat,l.lon],Math.max(map.getZoom(),6));grupo.zoomToShowLayer(m,()=>m.openTooltip())}const tipos=l.tipos.map(t=>(TIPOS_LUGAR[t]||TIPOS_LUGAR.mencionado).rotulo).join(' · ');const certeza=(CERTEZAS[l.certezaPrincipal]||CERTEZAS.ilustrativo).rotulo;detalhe.innerHTML=`<h3>${l.nome}</h3><p class="atlas-detalhe-conta">${l.obras.length} obra${l.obras.length>1?'s':''} do acervo passam por este lugar</p><p class="atlas-detalhe-tipos">${tipos} · ${certeza}</p><ul class="atlas-obras-aqui">${l.obras.map(o=>`<li><a href="obra.html?id=${o.id}"><strong>${o.titulo}</strong><span>${o.autor} · ${o.ano}</span></a></li>`).join('')}</ul>`}
document.getElementById('busca-lugar').addEventListener('input',e=>renderLista(e.target.value));renderLista();
})();
