(function(){
  const busca=document.getElementById('busca-autores'),lista=document.getElementById('lista-autores'),contador=document.getElementById('contador-autores'),metricas=document.getElementById('autores-metricas');if(!busca||!lista)return;
  const STORE='tl:autores:busca';
  const mapa=new Map();OBRAS.forEach(o=>{const atual=mapa.get(o.autor)||{nome:o.autor,obras:[],movimentos:new Set(),anos:[],lugares:new Set(),corpus:0};atual.obras.push(o);atual.movimentos.add(o.movimento);atual.anos.push(o.ano);(o.lugares||[]).forEach(l=>atual.lugares.add(l.nome));if(window.CORPUS_PROFUNDO&&window.CORPUS_PROFUNDO[o.id]){const c=window.CORPUS_PROFUNDO[o.id];atual.corpus+=(c.place_mentions||[]).length;(c.place_entities||[]).forEach(e=>atual.lugares.add(e.canonical_name))}mapa.set(o.autor,atual)});
  const autores=[...mapa.values()].sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR')),movimentosGlobais=new Set(OBRAS.map(o=>o.movimento)),territoriosGlobais=new Set();autores.forEach(a=>a.lugares.forEach(l=>territoriosGlobais.add(l)));
  if(metricas)metricas.innerHTML=`<div class="page-metric"><strong>${autores.length}</strong><span>autores</span></div><div class="page-metric"><strong>${OBRAS.length}</strong><span>obras</span></div><div class="page-metric"><strong>${movimentosGlobais.size}</strong><span>movimentos</span></div><div class="page-metric"><strong>${territoriosGlobais.size}</strong><span>territórios relacionados</span></div>`;
  try{busca.value=localStorage.getItem(STORE)||''}catch(_){ }
  const norm=s=>(s||'').toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,''),iniciais=nome=>nome.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  function render(){const q=norm(busca.value),dados=autores.filter(a=>!q||norm(a.nome).includes(q)||[...a.movimentos].some(m=>norm(m).includes(q)));contador.textContent=`${dados.length} ${dados.length===1?'autor':'autores'} no resultado.`;lista.innerHTML=dados.length?dados.map(a=>{const min=Math.min(...a.anos),max=Math.max(...a.anos);return `<a class="author-object" href="autor.html?nome=${encodeURIComponent(a.nome)}"><div class="author-monogram" aria-hidden="true">${iniciais(a.nome)}</div><div class="author-object__body"><span class="author-object__meta">${[...a.movimentos].join(' · ')}</span><h2 class="author-object__name">${a.nome}</h2><p class="author-object__stats">${a.obras.length} ${a.obras.length===1?'obra':'obras'} · ${a.lugares.size} território${a.lugares.size===1?'':'s'} · ${min===max?min:`${min}–${max}`}</p><div class="author-object__research"><span class="book-pill">Abrir perfil</span>${a.corpus?`<span class="book-pill">${a.corpus} ocorrências</span>`:''}</div></div></a>`}).join(''):'<div class="empty-state">Nenhum autor corresponde à busca.</div>'}
  busca.addEventListener('input',()=>{try{if(busca.value)localStorage.setItem(STORE,busca.value);else localStorage.removeItem(STORE)}catch(_){ }render()});render();
})();