(function(){
  const root=document.getElementById('biblioteca-estante');
  if(!root||typeof OBRAS==='undefined')return;
  const track=document.getElementById('bookshelf-track'),filters=document.getElementById('bookshelf-filters'),search=document.getElementById('bookshelf-search'),detail=document.getElementById('bookshelf-detail'),status=document.getElementById('bookshelf-status'),dots=document.getElementById('bookshelf-dots');
  const prev=root.querySelector('[data-bookshelf-prev]'),next=root.querySelector('[data-bookshelf-next]');
  const palette=[['#4b2417','#b77b42'],['#15382f','#b99a58'],['#6e211d','#d19a4e'],['#17344d','#95afbd'],['#7a593a','#d5b37b'],['#392b43','#b59a69'],['#3d4d2c','#c2a76d'],['#552d22','#d29156']];
  const norm=s=>(s||'').toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const movements=[...new Set(OBRAS.map(o=>o.movimento))];
  let activeMovement='',query='',selectedId=null,dragging=false,startX=0,startLeft=0;
  function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
  function coverStyle(o){const n=[...o.id].reduce((a,c)=>a+c.charCodeAt(0),0),p=palette[n%palette.length];return `--cover:${p[0]};--cover-accent:${p[1]}`}
  function filtered(){const q=norm(query);return OBRAS.filter(o=>(!activeMovement||o.movimento===activeMovement)&&(!q||norm(`${o.titulo} ${o.autor} ${o.movimento}`).includes(q)))}
  function renderFilters(){filters.innerHTML=`<button type="button" class="bookshelf-chip is-active" data-movement="" aria-pressed="true">Todas</button>${movements.map(m=>`<button type="button" class="bookshelf-chip" data-movement="${esc(m)}" aria-pressed="false">${esc(m)}</button>`).join('')}`}
  function render(){const list=filtered();if(!selectedId||!list.some(o=>o.id===selectedId))selectedId=list[0]?.id||null;track.innerHTML=list.map((o,i)=>`<article class="shelf-book${o.id===selectedId?' is-selected':''}" data-book-id="${esc(o.id)}" role="option" aria-selected="${o.id===selectedId}" tabindex="${o.id===selectedId?'0':'-1'}" style="${coverStyle(o)}"><button class="shelf-book__select" type="button" aria-label="Selecionar ${esc(o.titulo)}"><span class="shelf-book__cover"><span class="shelf-book__ornament" aria-hidden="true"></span><span class="shelf-book__movement">${esc(o.movimento)}</span><strong>${esc(o.titulo)}</strong><span>${esc(o.autor)}</span><small>${esc(o.anoLabel||o.ano)}</small></span></button><div class="shelf-book__label"><strong>${esc(o.titulo)}</strong><span>${esc(o.autor)}</span></div></article>`).join('');status.textContent=`${list.length} ${list.length===1?'obra disponível':'obras disponíveis'}`;renderDots(list);updateDetail();requestAnimationFrame(()=>selectedCard()?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'}))}
  function renderDots(list){const pages=Math.max(1,Math.ceil(list.length/5)),selected=Math.max(0,list.findIndex(o=>o.id===selectedId)),page=Math.floor(selected/5);dots.innerHTML=Array.from({length:pages},(_,i)=>`<button type="button" aria-label="Ir para grupo ${i+1}" aria-current="${i===page?'true':'false'}" data-dot="${i}"></button>`).join('')}
  function selectedCard(){return track.querySelector(`[data-book-id="${CSS.escape(selectedId||'')}"]`)}
  function select(id,{focus=false}={}){if(!id)return;selectedId=id;track.querySelectorAll('.shelf-book').forEach(card=>{const on=card.dataset.bookId===id;card.classList.toggle('is-selected',on);card.setAttribute('aria-selected',String(on));card.tabIndex=on?0:-1});updateDetail();renderDots(filtered());const card=selectedCard();card?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'});if(focus)card?.focus()}
  function updateDetail(){const o=OBRAS.find(x=>x.id===selectedId);if(!o){detail.innerHTML='<p>Nenhuma obra corresponde aos filtros.</p>';return}const reader=globalThis.READER_REGISTRY?.[o.id];detail.innerHTML=`<div class="bookshelf-detail__meta">${esc(o.movimento)} · ${esc(o.anoLabel||o.ano)}</div><h3>${esc(o.titulo)}</h3><p class="bookshelf-detail__author">${esc(o.autor)}</p><p>${esc(o.sinopse)}</p><div class="bookshelf-detail__actions"><a class="button button--light" href="obra.html?id=${encodeURIComponent(o.id)}">Ver obra</a>${reader?`<a class="button button--ghost" href="leitura.html?obra=${encodeURIComponent(o.id)}">Ler agora</a>`:''}</div>`}
  function step(dir){const list=filtered(),i=Math.max(0,list.findIndex(o=>o.id===selectedId)),nextIndex=Math.min(list.length-1,Math.max(0,i+dir));select(list[nextIndex]?.id,{focus:true})}
  filters.addEventListener('click',e=>{const b=e.target.closest('[data-movement]');if(!b)return;activeMovement=b.dataset.movement||'';filters.querySelectorAll('.bookshelf-chip').forEach(x=>{const on=x===b;x.classList.toggle('is-active',on);x.setAttribute('aria-pressed',String(on))});render()});
  search.addEventListener('input',()=>{query=search.value;render()});
  track.addEventListener('click',e=>{const card=e.target.closest('.shelf-book');if(card)select(card.dataset.bookId)});
  track.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();step(1)}else if(e.key==='ArrowLeft'){e.preventDefault();step(-1)}else if(e.key==='Home'){e.preventDefault();select(filtered()[0]?.id,{focus:true})}else if(e.key==='End'){e.preventDefault();select(filtered().at(-1)?.id,{focus:true})}else if(e.key==='Enter'){const o=OBRAS.find(x=>x.id===selectedId);if(o)location.href=`obra.html?id=${encodeURIComponent(o.id)}`}});
  prev.addEventListener('click',()=>step(-1));next.addEventListener('click',()=>step(1));
  dots.addEventListener('click',e=>{const b=e.target.closest('[data-dot]');if(!b)return;const item=filtered()[Number(b.dataset.dot)*5];if(item)select(item.id,{focus:true})});
  track.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;dragging=true;startX=e.clientX;startLeft=track.scrollLeft;track.setPointerCapture?.(e.pointerId)});
  track.addEventListener('pointermove',e=>{if(!dragging)return;track.scrollLeft=startLeft-(e.clientX-startX)});
  const endDrag=e=>{if(!dragging)return;dragging=false;track.releasePointerCapture?.(e.pointerId)};track.addEventListener('pointerup',endDrag);track.addEventListener('pointercancel',endDrag);
  renderFilters();render();
})();