// TERRITÓRIO LITERÁRIO — acervo de obras brasileiras em domínio público.
// Domínio público no Brasil: 70 anos após a morte do autor (Lei 9.610/98, art. 41).
// Os links de leitura seguem o padrão de URL do Wikisource em português por convenção
// de título — confira cada um antes de publicar o site.

const MOVIMENTOS = ["Barroco","Arcadismo","Romantismo","Realismo","Naturalismo","Parnasianismo","Simbolismo","Pré-Modernismo","Modernismo"];

const TIPOS_LUGAR = {
  narrativo:{rotulo:"Lugar narrativo",cor:"#a45535",corTexto:"#8a4529"},
  mencionado:{rotulo:"Lugar mencionado",cor:"#c48f6b",corTexto:"#8a5c3a"},
  historico:{rotulo:"Lugar histórico",cor:"#274c59",corTexto:"#274c59"},
  biografico:{rotulo:"Lugar biográfico",cor:"#b08a4a",corTexto:"#7a5a2c"},
  ficcional:{rotulo:"Lugar ficcional",cor:"#7a746a",corTexto:"#5c5850"}
};
const CERTEZAS={identificado:{rotulo:"Localização identificada",tracejado:false},ilustrativo:{rotulo:"Localização ilustrativa",tracejado:true}};
const ESCALAS={ponto:"Um local pontual",bairro:"Um bairro ou distrito",cidade:"Uma cidade ou vila",regiao:"Uma região, serra, vale, sertão, rio ou litoral",estado:"Um estado inteiro",rota:"Um trajeto entre pontos"};

const OBRAS = [
{id:"gregorio-de-matos-poemas",titulo:"Poemas satíricos e líricos (seleção)",autor:"Gregório de Matos",ano:1600,anoLabel:"sécs. XVII",morte:1696,movimento:"Barroco",sinopse:"O 'Boca do Inferno' baiano: sátira social afiada e lirismo religioso conflituoso, nos primórdios da poesia em língua portuguesa no Brasil.",link:"https://pt.wikisource.org/wiki/Autor:Gregório_de_Matos",lugares:[{nome:"Salvador, Bahia",lat:-12.9714,lon:-38.5014,tipo:"biografico",escala:"cidade",certeza:"ilustrativo",descricao:"A cidade que Gregório de Matos retratou — e escandalizou — com sua sátira mordaz."}]},
{id:"marilia-de-dirceu",titulo:"Marília de Dirceu",autor:"Tomás Antônio Gonzaga",ano:1792,morte:1810,movimento:"Arcadismo",sinopse:"Liras de amor escritas no exílio, em Moçambique, para a amada deixada em Vila Rica — o retrato mais lido do Arcadismo mineiro.",link:"https://pt.wikisource.org/wiki/Marília_de_Dirceu",lugares:[{nome:"Vila Rica (Ouro Preto), Minas Gerais",lat:-20.3855,lon:-43.5035,tipo:"narrativo",escala:"cidade",certeza:"ilustrativo",descricao:"Cenário do ciclo do ouro e da Inconfidência Mineira, de onde o poeta foi arrancado."}]},
{id:"cancao-do-exilio",titulo:"Canção do exílio e outros poemas",autor:"Gonçalves Dias",ano:1843,morte:1864,movimento:"Romantismo",sinopse:"'Minha terra tem palmeiras...' — o poema fundador da saudade nacionalista romântica.",link:"https://pt.wikisource.org/wiki/Canção_do_Exílio",lugares:[{nome:"Caxias, Maranhão",lat:-4.8656,lon:-43.3564,tipo:"biografico",escala:"cidade",certeza:"ilustrativo",descricao:"Terra natal do poeta, evocada à distância em versos escritos na Europa."}]},
{id:"navio-negreiro",titulo:"O navio negreiro e outros poemas",autor:"Castro Alves",ano:1869,morte:1871,movimento:"Romantismo",sinopse:"O poeta dos escravos leva o Atlântico para dentro do verso: a travessia negreira narrada como tragédia e denúncia.",link:"https://pt.wikisource.org/wiki/O_Navio_Negreiro",lugares:[{nome:"Litoral da Bahia",lat:-13.0059,lon:-38.5106,tipo:"historico",escala:"regiao",certeza:"ilustrativo",descricao:"A rota do tráfico negreiro ao largo da costa baiana, cenário do poema-denúncia."}]},
{id:"lira-dos-vinte-anos",titulo:"Lira dos vinte anos",autor:"Álvares de Azevedo",ano:1853,morte:1852,movimento:"Romantismo",sinopse:"Publicada postumamente aos vinte anos: o byronismo brasileiro em sua forma mais febril.",link:"https://pt.wikisource.org/wiki/Lira_dos_Vinte_Anos",lugares:[{nome:"São Paulo (Largo de São Francisco)",lat:-23.5505,lon:-46.6333,tipo:"biografico",escala:"ponto",certeza:"identificado",descricao:"Onde o poeta cursava Direito quando escreveu boa parte destes versos."}]},
{id:"primaveras",titulo:"Primaveras",autor:"Casimiro de Abreu",ano:1859,morte:1860,movimento:"Romantismo",sinopse:"'Meus oito anos': a infância perdida e a saudade da terra natal.",link:"https://pt.wikisource.org/wiki/Primaveras",lugares:[{nome:"Barra de São João, Rio de Janeiro",lat:-22.5808,lon:-41.9897,tipo:"biografico",escala:"cidade",certeza:"identificado",descricao:"A vila natal do poeta, cenário nostálgico de seus versos mais célebres."}]},
{id:"o-guarani",titulo:"O Guarani",autor:"José de Alencar",ano:1857,morte:1877,movimento:"Romantismo",sinopse:"Peri e Ceci entre a mata do vale do Paquequer e a Serra dos Órgãos: o romance fundador do indianismo romântico.",link:"https://pt.wikisource.org/wiki/O_Guarani",lugares:[{nome:"Casa do fidalgo D. Antônio de Mariz",lat:-22.47,lon:-43.12,tipo:"narrativo",escala:"ponto",certeza:"ilustrativo",descricao:"Às margens do rio Paquequer, no sopé da serra — onde a história tem início."},{nome:"Serra dos Órgãos",lat:-22.45,lon:-43.03,tipo:"narrativo",escala:"regiao",certeza:"ilustrativo",descricao:"Refúgio e cenário dos embates entre colonos e os aimorés."},{nome:"Alto da serra, desfecho",lat:-22.42,lon:-42.98,tipo:"narrativo",escala:"regiao",certeza:"ilustrativo",descricao:"O ponto mais alto da narrativa, onde a enchente encerra a saga de Peri e Ceci."}]},
{id:"iracema",titulo:"Iracema",autor:"José de Alencar",ano:1865,morte:1877,movimento:"Romantismo",sinopse:"A 'virgem dos lábios de mel' transforma a paisagem cearense em mito de origem.",link:"https://pt.wikisource.org/wiki/Iracema",lugares:[{nome:"Praia junto à foz do rio Ceará",lat:-3.692,lon:-38.589,tipo:"narrativo",escala:"regiao",certeza:"ilustrativo",descricao:"A costa cearense onde se cruzam as trajetórias de Iracema e Martim."},{nome:"Serra de Ibiapaba",lat:-3.35,lon:-41.1,tipo:"narrativo",escala:"regiao",certeza:"ilustrativo",descricao:"Território indígena associado à travessia e aos conflitos do romance."}]},
{id:"senhora",titulo:"Senhora",autor:"José de Alencar",ano:1875,morte:1877,movimento:"Romantismo",sinopse:"Aurélia Camargo transforma casamento e dinheiro em um jogo de poder no Rio de Janeiro imperial.",link:"https://pt.wikisource.org/wiki/Senhora",lugares:[{nome:"Rio de Janeiro",lat:-22.9068,lon:-43.1729,tipo:"narrativo",escala:"cidade",certeza:"ilustrativo",descricao:"A corte imperial, com seus salões e convenções sociais."}]},
{id:"lucíola",titulo:"Lucíola",autor:"José de Alencar",ano:1862,morte:1877,movimento:"Romantismo",sinopse:"Lúcia e Paulo atravessam desejo, culpa e convenção social na corte do Segundo Reinado.",link:"https://pt.wikisource.org/wiki/Lucíola",lugares:[{nome:"Rio de Janeiro",lat:-22.9068,lon:-43.1729,tipo:"narrativo",escala:"cidade",certeza:"ilustrativo",descricao:"A corte imperial, cenário dos encontros e julgamentos sociais."}]},
{id:"ursula",titulo:"Úrsula",autor:"Maria Firmina dos Reis",ano:1859,morte:1917,movimento:"Romantismo",sinopse:"Romance pioneiro de autoria feminina e negra no Brasil, com crítica direta à escravidão.",link:"https://pt.wikisource.org/wiki/Úrsula",lugares:[{nome:"Maranhão",lat:-5.0,lon:-45.0,tipo:"narrativo",escala:"estado",certeza:"ilustrativo",descricao:"O território maranhense onde se desenrola a narrativa."},{nome:"Aldeia junto ao rio Mearim",lat:-4.75,lon:-44.95,tipo:"narrativo",escala:"regiao",certeza:"ilustrativo",descricao:"Ambiente fluvial e rural ligado à ação do romance."}]},
{id:"inocencia",titulo:"Inocência",autor:"Visconde de Taunay",ano:1872,morte:1899,movimento:"Romantismo",sinopse:"Uma história de amor atravessada pelo isolamento e pela honra no interior do Brasil.",link:"https://pt.wikisource.org/wiki/Inocência",lugares:[{nome:"Sertão de Mato Grosso",lat:-20.0,lon:-54.0,tipo:"narrativo",escala:"regiao",certeza:"ilustrativo",descricao:"O sertão percorrido pelos personagens, eixo espacial do romance."}]},
{id:"escrava-isaura",titulo:"A Escrava Isaura",autor:"Bernardo Guimarães",ano:1875,morte:1884,movimento:"Romantismo",sinopse:"A jovem escravizada Isaura foge de uma fazenda fluminense e confronta os limites sociais do Império.",link:"https://pt.wikisource.org/wiki/A_Escrava_Isaura",lugares:[{nome:"Campos dos Goytacazes",lat:-21.7523,lon:-41.3304,tipo:"narrativo",escala:"cidade",certeza:"ilustrativo",descricao:"Região de fazendas açucareiras onde começa a história."},{nome:"Recife",lat:-8.0476,lon:-34.877,tipo:"narrativo",escala:"cidade",certeza:"ilustrativo",descricao:"Destino da fuga de Isaura e espaço de transformação da narrativa."}]},
{id:"moreninha",titulo:"A Moreninha",autor:"Joaquim Manuel de Macedo",ano:1844,morte:1882,movimento:"Romantismo",sinopse:"Um romance de juventude, promessa e reencontro numa ilha da baía do Rio de Janeiro.",link:"https://pt.wikisource.org/wiki/A_Moreninha",lugares:[{nome:"Ilha de Paquetá",lat:-22.7626,lon:-43.1086,tipo:"narrativo",escala:"bairro",certeza:"identificado",descricao:"A ilha onde se passa a maior parte da ação romântica."}]},
{id:"memorias-sargento-milicias",titulo:"Memórias de um Sargento de Milícias",autor:"Manuel Antônio de Almeida",ano:1854,morte:1861,movimento:"Romantismo",sinopse:"Leonardo circula pelas ruas populares do Rio joanino, entre malandragem e ascensão social.",link:"https://pt.wikisource.org/wiki/Memórias_de_um_Sargento_de_Milícias",lugares:[{nome:"Rio de Janeiro colonial",lat:-22.9068,lon:-43.1729,tipo:"historico",escala:"cidade",certeza:"ilustrativo",descricao:"A cidade no tempo de D. João VI, vista por suas ruas e personagens populares."}]},
{id:"memorias-postumas",titulo:"Memórias Póstumas de Brás Cubas",autor:"Machado de Assis",ano:1881,morte:1908,movimento:"Realismo",sinopse:"Um defunto-autor reconstrói sua vida e a sociedade carioca com ironia implacável.",link:"https://pt.wikisource.org/wiki/Memórias_Póstumas_de_Brás_Cubas",lugares:[{nome:"Catumbi",lat:-22.918,lon:-43.195,tipo:"narrativo",escala:"bairro",certeza:"identificado",descricao:"Bairro associado ao funeral e à memória inicial de Brás Cubas."},{nome:"Tijuca",lat:-22.925,lon:-43.238,tipo:"narrativo",escala:"bairro",certeza:"identificado",descricao:"Área de chácaras e deslocamentos recorrentes na narrativa."},{nome:"Rua do Ouvidor",lat:-22.903,lon:-43.177,tipo:"narrativo",escala:"ponto",certeza:"identificado",descricao:"Eixo da vida social e urbana da corte."}]},
{id:"dom-casmurro",titulo:"Dom Casmurro",autor:"Machado de Assis",ano:1899,morte:1908,movimento:"Realismo",sinopse:"Bentinho reconstrói sua juventude, Capitu e uma memória que talvez não seja confiável.",link:"https://pt.wikisource.org/wiki/Dom_Casmurro",lugares:[{nome:"Engenho Novo, Rio de Janeiro",lat:-22.902,lon:-43.269,tipo:"narrativo",escala:"bairro",certeza:"identificado",descricao:"Bairro do narrador envelhecido e ponto de partida de suas memórias."}]},
{id:"quincas-borba",titulo:"Quincas Borba",autor:"Machado de Assis",ano:1891,morte:1908,movimento:"Realismo",sinopse:"Rubião leva ao Rio uma fortuna e o Humanitismo, mas encontra uma sociedade que o devora.",link:"https://pt.wikisource.org/wiki/Quincas_Borba",lugares:[{nome:"Botafogo",lat:-22.9519,lon:-43.1809,tipo:"narrativo",escala:"bairro",certeza:"identificado",descricao:"Bairro de residência e circulação social na narrativa."}]},
{id:"esau-e-jaco",titulo:"Esaú e Jacó",autor:"Machado de Assis",ano:1904,morte:1908,movimento:"Realismo",sinopse:"Dois irmãos rivais atravessam a transição do Império à República entre afetos e política.",link:"https://pt.wikisource.org/wiki/Esaú_e_Jacó",lugares:[{nome:"Rio de Janeiro",lat:-22.9068,lon:-43.1729,tipo:"historico",escala:"cidade",certeza:"ilustrativo",descricao:"A capital durante a transição entre Império e República."}]},
{id:"memorial-de-aires",titulo:"Memorial de Aires",autor:"Machado de Assis",ano:1908,morte:1908,movimento:"Realismo",sinopse:"O conselheiro Aires registra em diário afetos, ausências e a velhice no Rio do início do século XX.",link:"https://pt.wikisource.org/wiki/Memorial_de_Aires",lugares:[{nome:"Rio de Janeiro",lat:-22.9068,lon:-43.1729,tipo:"narrativo",escala:"cidade",certeza:"ilustrativo",descricao:"A cidade observada pelo diário do conselheiro Aires."}]},
{id:"iaiá-garcia",titulo:"Iaiá Garcia",autor:"Machado de Assis",ano:1878,morte:1908,movimento:"Realismo",sinopse:"Relações familiares, amor e posição social no Brasil imperial.",link:"https://pt.wikisource.org/wiki/Iaiá_Garcia",lugares:[{nome:"Rio de Janeiro",lat:-22.9068,lon:-43.1729,tipo:"historico",escala:"cidade",certeza:"ilustrativo",descricao:"Pano de fundo social do romance."}]},
{id:"o-cortico",titulo:"O Cortiço",autor:"Aluísio Azevedo",ano:1890,morte:1913,movimento:"Naturalismo",sinopse:"Um cortiço carioca se torna organismo social, palco de ambição, desejo, violência e exploração.",link:"https://pt.wikisource.org/wiki/O_Cortiço",lugares:[{nome:"Botafogo, Rio de Janeiro",lat:-22.9519,lon:-43.1809,tipo:"narrativo",escala:"bairro",certeza:"identificado",descricao:"Área onde o romance situa o cortiço e suas relações sociais."}]},
{id:"o-mulato",titulo:"O Mulato",autor:"Aluísio Azevedo",ano:1881,morte:1913,movimento:"Naturalismo",sinopse:"Preconceito racial, religião e elite provincial entram em conflito no Maranhão oitocentista.",link:"https://pt.wikisource.org/wiki/O_Mulato",lugares:[{nome:"São Luís, Maranhão",lat:-2.5307,lon:-44.3068,tipo:"narrativo",escala:"cidade",certeza:"ilustrativo",descricao:"A cidade provincial cuja sociedade é dissecada pelo romance."}]},
{id:"casa-de-pensao",titulo:"Casa de Pensão",autor:"Aluísio Azevedo",ano:1884,morte:1913,movimento:"Naturalismo",sinopse:"Um jovem provinciano chega ao Rio e é absorvido pela vida de uma pensão e suas relações de interesse.",link:"https://pt.wikisource.org/wiki/Casa_de_Pensão",lugares:[{nome:"Rio de Janeiro",lat:-22.9068,lon:-43.1729,tipo:"narrativo",escala:"cidade",certeza:"ilustrativo",descricao:"A cidade em expansão e suas relações sociais."}]},
{id:"o-ateneu",titulo:"O Ateneu",autor:"Raul Pompeia",ano:1888,morte:1895,movimento:"Naturalismo",sinopse:"Um menino ingressa em um internato e descobre a crueldade adulta em miniatura.",link:"https://pt.wikisource.org/wiki/O_Ateneu",lugares:[{nome:"Rio de Janeiro",lat:-22.9068,lon:-43.1729,tipo:"narrativo",escala:"cidade",certeza:"ilustrativo",descricao:"O internato fictício, inspirado em colégios reais da corte."}]},
{id:"bom-crioulo",titulo:"Bom-Crioulo",autor:"Adolfo Caminha",ano:1895,morte:1897,movimento:"Naturalismo",sinopse:"Na Marinha do fim do século XIX, um marinheiro negro se apaixona por um grumete branco.",link:"https://pt.wikisource.org/wiki/Bom-Crioulo",lugares:[{nome:"Rio de Janeiro (Marinha)",lat:-22.896,lon:-43.166,tipo:"narrativo",escala:"cidade",certeza:"ilustrativo",descricao:"Os navios e quartéis da Marinha, cenário do romance."}]},
{id:"a-normalista",titulo:"A Normalista",autor:"Adolfo Caminha",ano:1893,morte:1897,movimento:"Naturalismo",sinopse:"Uma jovem estudante é seduzida e abandonada pelo padrinho: retrato cru da hipocrisia moral.",link:"https://pt.wikisource.org/wiki/A_Normalista",lugares:[{nome:"Fortaleza, Ceará",lat:-3.7172,lon:-38.5433,tipo:"narrativo",escala:"cidade",certeza:"ilustrativo",descricao:"A capital cearense onde se desenrola a queda moral de Maria do Carmo."}]},
{id:"poesias-bilac",titulo:"Poesias (seleção)",autor:"Olavo Bilac",ano:1888,morte:1918,movimento:"Parnasianismo",sinopse:"Versos lapidados e culto parnasiano à perfeição formal.",link:"https://pt.wikisource.org/wiki/Autor:Olavo_Bilac",lugares:[{nome:"Rio de Janeiro",lat:-22.9068,lon:-43.1729,tipo:"biografico",escala:"cidade",certeza:"ilustrativo",descricao:"A vida literária da capital, entre jornais e salões."}]},
{id:"broqueis",titulo:"Broquéis",autor:"Cruz e Sousa",ano:1893,morte:1898,movimento:"Simbolismo",sinopse:"Musicalidade, angústia existencial e inovação simbolista.",link:"https://pt.wikisource.org/wiki/Broquéis",lugares:[{nome:"Desterro (Florianópolis), Santa Catarina",lat:-27.5954,lon:-48.548,tipo:"biografico",escala:"cidade",certeza:"ilustrativo",descricao:"Cidade natal do poeta."}]},
{id:"contos-populares-brasil",titulo:"Contos Populares do Brasil",autor:"Sílvio Romero",ano:1885,morte:1914,movimento:"Realismo",sinopse:"Registro pioneiro da tradição oral brasileira.",link:"https://pt.wikisource.org/wiki/Contos_Populares_do_Brasil",lugares:[{nome:"Lagarto, Sergipe",lat:-10.9167,lon:-37.6667,tipo:"biografico",escala:"cidade",certeza:"identificado",descricao:"Terra natal do folclorista."}]},
{id:"os-sertoes",titulo:"Os Sertões",autor:"Euclides da Cunha",ano:1902,morte:1909,movimento:"Pré-Modernismo",sinopse:"Reportagem, ciência e épico se fundem no relato da Guerra de Canudos.",link:"https://pt.wikisource.org/wiki/Os_Sertões",lugares:[{nome:"Salvador, ponto de partida das expedições",lat:-12.9714,lon:-38.5014,tipo:"narrativo",escala:"cidade",certeza:"ilustrativo",descricao:"De onde partem expedições rumo ao sertão."},{nome:"Queimadas",lat:-10.97,lon:-39.62,tipo:"narrativo",escala:"cidade",certeza:"identificado",descricao:"Base de apoio das tropas."},{nome:"Monte Santo",lat:-10.43,lon:-39.34,tipo:"narrativo",escala:"cidade",certeza:"identificado",descricao:"Último povoado antes do avanço final."},{nome:"Canudos",lat:-9.9,lon:-39.02,tipo:"narrativo",escala:"cidade",certeza:"identificado",descricao:"O arraial de Antônio Conselheiro."}]},
{id:"policarpo-quaresma",titulo:"Triste Fim de Policarpo Quaresma",autor:"Lima Barreto",ano:1915,morte:1922,movimento:"Pré-Modernismo",sinopse:"Um funcionário público patriota tenta, em vão, provar seu amor ao Brasil.",link:"https://pt.wikisource.org/wiki/Triste_Fim_de_Policarpo_Quaresma",lugares:[{nome:"Bairro de Todos os Santos, Rio de Janeiro",lat:-22.899,lon:-43.282,tipo:"narrativo",escala:"bairro",certeza:"identificado",descricao:"Onde Policarpo vive e estuda tupi-guarani."},{nome:"Sítio em Curuzu, Jacarepaguá",lat:-22.95,lon:-43.36,tipo:"narrativo",escala:"ponto",certeza:"identificado",descricao:"Para onde se muda para provar a fertilidade da terra."},{nome:"Ilha das Cobras",lat:-22.896,lon:-43.166,tipo:"narrativo",escala:"ponto",certeza:"identificado",descricao:"Prisão militar onde a trajetória do personagem se encerra."}]},
{id:"recordacoes-isaias-caminha",titulo:"Recordações do Escrivão Isaías Caminha",autor:"Lima Barreto",ano:1909,morte:1922,movimento:"Pré-Modernismo",sinopse:"Um jovem mestiço enfrenta o racismo velado da imprensa carioca.",link:"https://pt.wikisource.org/wiki/Recordações_do_Escrivão_Isaías_Caminha",lugares:[{nome:"Rio de Janeiro",lat:-22.9068,lon:-43.1729,tipo:"narrativo",escala:"cidade",certeza:"ilustrativo",descricao:"As redações de jornal e a vida urbana da capital."}]},
{id:"urupes",titulo:"Urupês",autor:"Monteiro Lobato",ano:1918,morte:1948,movimento:"Pré-Modernismo",sinopse:"O caipira Jeca Tatu nasce nestas páginas.",link:"https://pt.wikisource.org/wiki/Urupês",lugares:[{nome:"Vale do Paraíba, São Paulo",lat:-23.0264,lon:-45.5556,tipo:"narrativo",escala:"regiao",certeza:"ilustrativo",descricao:"O interior paulista observado por Lobato."}]},
{id:"contos-gauchescos",titulo:"Contos Gauchescos",autor:"João Simões Lopes Neto",ano:1912,morte:1916,movimento:"Pré-Modernismo",sinopse:"O peão Blau Nunes narra causos do pampa.",link:"https://pt.wikisource.org/wiki/Contos_Gauchescos",lugares:[{nome:"Pelotas, Rio Grande do Sul",lat:-31.7654,lon:-52.3376,tipo:"narrativo",escala:"regiao",certeza:"ilustrativo",descricao:"O pampa gaúcho, terra do narrador Blau Nunes."}]},
{id:"macunaima",titulo:"Macunaíma",autor:"Mário de Andrade",ano:1928,morte:1945,movimento:"Modernismo",sinopse:"'Herói sem nenhum caráter': Macunaíma atravessa o Brasil atrás de sua muiraquitã.",link:"https://pt.wikisource.org/wiki/Macunaíma",lugares:[{nome:"Fundo do mato-virgem, Roraima",lat:2.8,lon:-60.7,tipo:"narrativo",escala:"regiao",certeza:"ilustrativo",descricao:"Onde Macunaíma nasce."},{nome:"Travessia rumo ao Sudeste",lat:-8,lon:-50,tipo:"narrativo",escala:"rota",certeza:"ilustrativo",descricao:"A grande travessia em busca da muiraquitã."},{nome:"São Paulo",lat:-23.5505,lon:-46.6333,tipo:"narrativo",escala:"cidade",certeza:"ilustrativo",descricao:"A cidade grande e a modernidade."}]},
{id:"memorias-sentimentais-joao-miramar",titulo:"Memórias Sentimentais de João Miramar",autor:"Oswald de Andrade",ano:1924,morte:1954,movimento:"Modernismo",sinopse:"Narrativa fragmentada em miniaturas telegráficas.",link:"https://pt.wikisource.org/wiki/Memórias_Sentimentais_de_João_Miramar",lugares:[{nome:"São Paulo",lat:-23.5505,lon:-46.6333,tipo:"narrativo",escala:"cidade",certeza:"ilustrativo",descricao:"A cidade que explode em modernidade."}]},
{id:"canaa",titulo:"Canaã",autor:"Graça Aranha",ano:1902,morte:1931,movimento:"Pré-Modernismo",sinopse:"Dois imigrantes alemães discutem o destino do Brasil nas colônias do Espírito Santo.",link:"https://pt.wikisource.org/wiki/Canaã",lugares:[{nome:"Santa Leopoldina, Espírito Santo",lat:-20.0989,lon:-40.5322,tipo:"narrativo",escala:"cidade",certeza:"identificado",descricao:"Colônia de imigrantes alemães que inspirou o cenário do romance."}]}
];
