(async function(){
  const params=new URLSearchParams(location.search),obraId=params.get('obra');
  const config=typeof readerConfig==='function'?readerConfig(obraId):null;
  const els={title:document.getElementById('reader-book-title'),author:document.getElementById('reader-book-author'),edition:document.getElementById('reader-edition'),chapter:document.getElementById('reader-chapter-title'),chapterNo:document.getElementById('reader-chapter-number'),text:document.getElementById('reader-text'),index:document.getElementById('reader-index'),prev:document.getElementById('reader-prev'),next:document.getElementById('reader-next'),back:document.getElementById('reader-back-work'),search:document.getElementById('reader-search'),results:document.getElementById('reader-search-results'),sourceCopy:document.getElementById('reader-source-copy'),sourceLink:document.getElementById('reader-source-link'),atlas:document.getElementById('reader-atlas-link'),live:document.getElementById('reader-live'),sidebar:document.getElementById('reader-sidebar'),toggle:document.getElementById('reader-index-toggle'),close:document.getElementById('reader-index-close'),backdrop:document.getElementById('reader-backdrop'),progressText:document.getElementById('reader-progress-text'),progressBar:document.getElementById('reader-progress-bar')};
  const safeGet=k=>{try{return localStorage.getItem(k)}catch{return null}},safeSet=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
  const mobile=matchMedia('(max-width: 800px)');
  function setDrawer(open,{restoreFocus=false}={}){if(!els.sidebar||!els.toggle||!els.backdrop)return;const active=mobile.matches&&open;els.sidebar.classList.toggle('is-open',active);els.sidebar.setAttribute('aria-hidden',String(mobile.matches?!active:false));els.toggle.setAttribute('aria-expanded',String(active));els.backdrop.hidden=!active;document.body.classList.toggle('reader-drawer-open',active);if(active)requestAnimationFrame(()=>els.search?.focus());else if(restoreFocus)els.toggle.focus()}
  function syncDrawer(){if(mobile.matches)setDrawer(false);else{els.sidebar?.classList.remove('is-open');els.sidebar?.setAttribute('aria-hidden','false');els.toggle?.setAttribute('aria-expanded','false');if(els.backdrop)els.backdrop.hidden=true;document.body.classList.remove('reader-drawer-open')}}
  els.toggle?.addEventListener('click',()=>setDrawer(els.toggle.getAttribute('aria-expanded')!=='true'));
  els.close?.addEventListener('click',()=>setDrawer(false,{restoreFocus:true}));
  els.backdrop?.addEventListener('click',()=>setDrawer(false,{restoreFocus:true}));
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&els.toggle?.getAttribute('aria-expanded')==='true')setDrawer(false,{restoreFocus:true})});
  mobile.addEventListener?.('change',syncDrawer);syncDrawer();
  function fail(message){els.chapter.textContent='Leitura indisponível';els.text.textContent=message;if(els.progressText)els.progressText.textContent='Leitura indisponível';document.body.dataset.readerReady='true'}
  if(!config){fail('Esta obra ainda não possui uma edição integral aprovada para leitura local.');return}
  els.title.textContent=config.titulo;els.author.textContent=config.autor;els.edition.textContent=config.edicao;els.back.href=`obra.html?id=${encodeURIComponent(config.id)}`;els.sourceCopy.textContent=`Edição-base: ${config.edicao}. Texto digital preparado a partir de ${config.source.provider}, eBook #${config.source.ebook}, com proveniência registrada pelo projeto.`;els.sourceLink.href=config.sourceReference||config.source.url;
  let response;try{response=await fetch(config.localPath,{cache:'force-cache'})}catch{fail('Não foi possível carregar o texto desta edição.');return}if(!response.ok){fail(`O arquivo local da obra não está disponível (HTTP ${response.status}).`);return}const raw=await response.text();
  function chapterMatches(text,format){
    const patterns={
      'capitulo-roman':/^CAPITULO\s+([IVXLCDM]+)\s*\r?\n+(?:\s*\r?\n)*([^\r\n]+)\s*\r?\n/gm,
      'roman-heading':/^([IVXLCDM]+)\.?\s*\r?\n+(?:\s*\r?\n)*([^\r\n]+)\s*\r?\n/gm,
      'roman-untitled':/^([IVXLCDM]+)\.?\s*\r?\n/gm,
      'part-roman-heading':/^(?:(PRIMEIRA|SEGUNDA|TERCEIRA|QUARTA) PARTE\s*\r?\n+(?:\s*\r?\n)*(?:[^\r\n]+\s*\r?\n+(?:\s*\r?\n)*)?)?([IVXLCDM]+)\.?\s*\r?\n+(?:\s*\r?\n)*([^\r\n]+)\s*\r?\n/gm
    };
    const re=patterns[format]||patterns['capitulo-roman'];
    return [...text.matchAll(re)];
  }
  const matches=chapterMatches(raw,config.chapterFormat);if(!matches.length){fail('A estrutura de capítulos desta edição não pôde ser reconhecida.');return}
  const romanValue=s=>{const m={I:1,V:5,X:10,L:50,C:100,D:500,M:1000};let n=0;for(let i=0;i<s.length;i++)n+=(m[s[i]]<(m[s[i+1]]||0)?-m[s[i]]:m[s[i]]);return n};
  let currentPart=1;
  const partNumber=name=>({PRIMEIRA:1,SEGUNDA:2,TERCEIRA:3,QUARTA:4}[name]||currentPart);
  const chapters=matches.map((m,i)=>{
    const end=i+1<matches.length?matches[i+1].index:raw.length;
    if(config.chapterFormat==='part-roman-heading'){
      if(m[1])currentPart=partNumber(m[1]);
      return {roman:m[2],number:i+1,title:m[3].trim(),part:currentPart,body:raw.slice(m.index+m[0].length,end).trim()};
    }
    return {roman:m[1],number:romanValue(m[1]),title:config.chapterFormat==='roman-untitled'?`Capítulo ${m[1]}`:m[2].trim(),body:raw.slice(m.index+m[0].length,end).trim()};
  });
  const key=`tl-reader:${config.id}:chapter`,explicit=params.has('capitulo');let requested=Number(params.get('capitulo')||(explicit?'':safeGet(key))||1);if(!chapters.some(c=>c.number===requested))requested=chapters[0].number;
  let fontSize=Number(safeGet('tl-reader:font-size')||1.18);if(!Number.isFinite(fontSize))fontSize=1.18;const applyFont=()=>document.documentElement.style.setProperty('--reader-font-size',`${fontSize}rem`);applyFont();
  function textParagraphs(body){els.text.innerHTML='';body.split(/\r?\n\s*\r?\n+/).map(x=>x.replace(/\s*\r?\n\s*/g,' ').trim()).filter(Boolean).forEach(t=>{const p=document.createElement('p');p.textContent=t;els.text.appendChild(p)})}
  function updateStructuredData(ch){document.querySelectorAll('script[data-reader-jsonld]').forEach(x=>x.remove());const canonical=`https://evybandeca.github.io/territorio-literario/leitura.html?obra=${encodeURIComponent(config.id)}&capitulo=${ch.number}`;let link=document.querySelector('link[rel="canonical"]');if(!link){link=document.createElement('link');link.rel='canonical';document.head.appendChild(link)}link.href=canonical;const chapterLabel=ch.part?`Parte ${ch.part}, capítulo ${ch.roman}`:`Capítulo ${ch.roman}`;document.title=`${config.titulo} — ${chapterLabel} — Território Literário`;const meta=document.querySelector('meta[name="description"]');if(meta)meta.content=`Leia ${config.titulo}, de ${config.autor}, ${chapterLabel.toLowerCase()}: ${ch.title}.`;const data=[{'@context':'https://schema.org','@type':'Book',name:config.titulo,author:{'@type':'Person',name:config.autor},datePublished:String(config.ano),url:`https://evybandeca.github.io/territorio-literario/leitura.html?obra=${encodeURIComponent(config.id)}`},{'@context':'https://schema.org','@type':'Chapter',name:ch.title,position:ch.number,isPartOf:{'@type':'Book',name:config.titulo},url:canonical}];for(const item of data){const s=document.createElement('script');s.type='application/ld+json';s.dataset.readerJsonld='true';s.textContent=JSON.stringify(item);document.head.appendChild(s)}}
  async function updateAtlas(ch){els.atlas.hidden=true;if(typeof loadCorpusById!=='function')return;try{const corpus=await loadCorpusById(config.id),mentions=(corpus?.place_mentions||[]).filter(m=>Number(m.capitulo)===ch.number);if(!mentions.length)return;els.atlas.href=`atlas.html?busca=${encodeURIComponent(mentions[0].canonical_name||mentions[0].nome_textual||config.titulo)}`;els.atlas.textContent=mentions.length===1?'Ver 1 lugar deste capítulo no Atlas':`Ver ${mentions.length} lugares deste capítulo no Atlas`;els.atlas.hidden=false}catch{}}
  function hrefFor(n){return `leitura.html?obra=${encodeURIComponent(config.id)}&capitulo=${n}`}
  function chapterLabel(ch){return ch.part?`Parte ${ch.part} · ${ch.roman}`:ch.roman}
  function searchLabel(ch){return ch.part?chapterLabel(ch):`Cap. ${ch.roman}`}
  function renderIndex(active){els.index.innerHTML='';for(const ch of chapters){const li=document.createElement('li'),a=document.createElement('a');a.href=hrefFor(ch.number);a.textContent=`${chapterLabel(ch)} · ${ch.title}`;if(ch.number===active)a.setAttribute('aria-current','page');li.appendChild(a);els.index.appendChild(li)}}
  function updateProgress(index){const current=index+1,total=chapters.length,percentage=Math.max(0,Math.min(100,Math.round(current/total*100)));if(els.progressText)els.progressText.textContent=`Capítulo ${current} de ${total} · ${percentage}%`;if(els.progressBar)els.progressBar.style.width=`${percentage}%`}
  async function render(number,{focus=false,push=false}={}){const ch=chapters.find(c=>c.number===number)||chapters[0],i=chapters.indexOf(ch);els.chapterNo.textContent=ch.part?`Parte ${ch.part} · Capítulo ${ch.roman}`:`Capítulo ${ch.roman}`;els.chapter.textContent=ch.title;textParagraphs(ch.body);renderIndex(ch.number);updateProgress(i);els.prev.hidden=i===0;els.next.hidden=i===chapters.length-1;if(i>0)els.prev.href=hrefFor(chapters[i-1].number);if(i<chapters.length-1)els.next.href=hrefFor(chapters[i+1].number);safeSet(key,String(ch.number));safeSet('tl-reader:last',JSON.stringify({workId:config.id,chapter:ch.number,title:config.titulo}));if(push)history.pushState({chapter:ch.number},'',hrefFor(ch.number));updateStructuredData(ch);updateAtlas(ch);els.live.textContent=`${els.chapterNo.textContent}: ${ch.title}`;if(focus){els.chapter.focus();scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}document.body.dataset.readerReady='true'}
  function intercept(a){a.addEventListener('click',e=>{if(e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;const u=new URL(a.href,location.href);if(u.pathname!==location.pathname)return;e.preventDefault();render(Number(u.searchParams.get('capitulo')),{focus:true,push:true})})}
  intercept(els.prev);intercept(els.next);els.index.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;e.preventDefault();const u=new URL(a.href,location.href);setDrawer(false);render(Number(u.searchParams.get('capitulo')),{focus:true,push:true})});
  addEventListener('popstate',()=>{const n=Number(new URLSearchParams(location.search).get('capitulo')||1);render(n,{focus:true})});
  document.getElementById('reader-font-inc').addEventListener('click',()=>{fontSize=Math.min(1.6,fontSize+.08);applyFont();safeSet('tl-reader:font-size',String(fontSize))});document.getElementById('reader-font-dec').addEventListener('click',()=>{fontSize=Math.max(.9,fontSize-.08);applyFont();safeSet('tl-reader:font-size',String(fontSize))});
  els.search.addEventListener('input',()=>{const q=els.search.value.trim().toLocaleLowerCase('pt-BR');els.results.innerHTML='';if(q.length<2)return;const found=chapters.filter(c=>(c.title+' '+c.body).toLocaleLowerCase('pt-BR').includes(q)).slice(0,20);if(!found.length){els.results.textContent='Nenhum capítulo encontrado.';return}const frag=document.createDocumentFragment();for(const ch of found){const a=document.createElement('a');a.href=hrefFor(ch.number);a.textContent=`${searchLabel(ch)} · ${ch.title}`;a.addEventListener('click',e=>{e.preventDefault();setDrawer(false);render(ch.number,{focus:true,push:true});els.search.value='';els.results.innerHTML=''});frag.appendChild(a)}els.results.appendChild(frag)});
  await render(requested);
})();
