(function(){
const params=new URLSearchParams(location.search),id=params.get('id'),obra=OBRAS.find(o=>o.id===id),corpo=document.getElementById('obra-corpo'),main=document.getElementById('conteudo');
if(!obra){document.getElementById('titulo-obra').textContent='Obra não encontrada';document.getElementById('sinopse-obra').textContent='Não achamos essa obra no acervo.';document.getElementById('link-leitura').style.display='none';document.querySelector('.work-cover-object')?.setAttribute('hidden','');return}
document.title=`${obra.titulo} — Território Literário`;document.getElementById('page-title').textContent=document.title;document.getElementById('selo-movimento').textContent=obra.movimento;document.getElementById('titulo-obra').textContent=obra.titulo;document.getElementById('autor-obra').textContent=`${obra.autor} · ${obra.anoLabel||obra.ano}`;document.getElementById('sinopse-obra').textContent=obra.sinopse;document.getElementById('link-leitura').href=obra.link;
document.getElementById('obra-cover-title').textContent=obra.titulo;document.getElementById('obra-cover-author').textContent=obra.autor;document.getElementById('obra-cover-year').textContent=`${obra.movimento} · ${obra.anoLabel||obra.ano}`;const atlasLink=document.getElementById('link-atlas')||document.querySelector('.work-hero__actions a[href="atlas.html"]');if(atlasLink)atlasLink.href=`atlas.html?busca=${encodeURIComponent(obra.titulo)}`;
const reader=typeof readerConfig==='function'?readerConfig(obra.id):null,actions=document.querySelector('.work-hero__actions');if(actions)actions.setAttribute('data-reader-available',String(Boolean(reader)));if(!reader){const link=document.getElementById('link-leitura');if(link){link.textContent='Consultar edição externa';link.href=obra.link;link.target='_blank';link.rel='noopener'}}
const corpus=window.CORPUS_PROFUNDO&&window.CORPUS_PROFUNDO[obra.id],mencoes=corpus?.place_mentions||[],entidades=corpus?.place_entities||[],estrutura=corpus?.estrutura||{},unidades=estrutura.capitulos_auditados||estrutura.unidades_auditadas||[],personagens=corpus?.personagens||[],eventos=corpus?.eventos||[],percursos=corpus?.percursos||[];
const facts=document.getElementById('obra-facts');if(facts)facts.innerHTML=`<div class="work-fact"><span>Autor</span><strong>${obra.autor}</strong></div><div class="work-fact"><span>Publicação</span><strong>${obra.anoLabel||obra.ano}</strong></div><div class="work-fact"><span>Movimento</span><strong>${obra.movimento}</strong></div><div class="work-fact"><span>Território público</span><strong>${obra.lugares?.length||0} ponto${(obra.lugares?.length||0)===1?'':'s'}</strong></div>`;
const strip=document.getElementById('obra-research-strip');if(strip)strip.innerHTML=corpus?`<div class="work-research-stat"><strong>${entidades.length}</strong><span>entidades</span></div><div class="work-research-stat"><strong>${mencoes.length}</strong><span>ocorrências</span></div><div class="work-research-stat"><strong>${unidades.length}</strong><span>unidades auditadas</span></div><div class="work-research-stat"><strong>${personagens.length}</strong><span>personagens</span></div>`:`<div class="work-research-stat"><strong>${obra.lugares?.length||0}</strong><span>lugares publicados</span></div><div class="work-research-stat"><strong>Editorial</strong><span>nível de cobertura</span></div>`;
const territorySummary=document.getElementById('obra-territory-summary');if(territorySummary){const publicPlaces=obra.lugares?.length||0,verified=entidades.length||publicPlaces,occurrences=mencoes.length;territorySummary.innerHTML=`<div><span class="eyebrow">Leitura e território</span><h2>Entre no texto ou explore sua geografia</h2><p>${reader?'Leitura integral hospedada no portal com retomada de capítulo.':'A leitura integral ainda depende de fonte externa.'} O território mantém somente localizações publicáveis e evidências auditadas.</p></div><div class="work-territory-summary__metrics"><strong>${verified}</strong><span>${verified===1?'lugar estruturado':'lugares estruturados'}</span>${occurrences?`<strong>${occurrences}</strong><span>ocorrências textuais</span>`:''}</div>`}
const indice=typeof construirIndiceLugares==='function'?construirIndiceLugares():[];function outras(nome){const e=indice.find(l=>l.nome===nome);return e?e.obras.filter(o=>o.id!==obra.id):[]}
if(obra.lugares&&obra.lugares.length){const bloco=document.createElement('section');bloco.className='mapa-bloco obra-secao';bloco.innerHTML=`<div class="section-heading"><div><div class="eyebrow">Território publicado</div><h2>${obra.lugares.length>1?`${obra.lugares.length} lugares cartografados`:'1 lugar cartografado'}</h2></div><p>Somente pontos já aprovados para visualização pública; lugares sem geocodificação defensável permanecem nas evidências textuais.</p></div><div id="mapa" aria-label="Mapa dos lugares publicados da obra"></div><ol class="lugares" id="lista-lugares"></ol>`;corpo.appendChild(bloco);const lista=bloco.querySelector('#lista-lugares');obra.lugares.forEach(l=>{const c=TIPOS_LUGAR[l.tipo]||TIPOS_LUGAR.mencionado,z=CERTEZAS[l.certeza]||CERTEZAS.ilustrativo,o=outras(l.nome),li=document.createElement('li');li.style.setProperty('--marca-cor',c.corTexto);li.innerHTML=`<span class="tipo-tag">${c.rotulo}</span><span class="certeza-tag">${z.rotulo}</span><strong>${l.nome}</strong><span class="descricao">${l.descricao}</span>${o.length?`<div class="outras-obras-aqui">Também neste território: ${o.map(x=>`<a href="obra.html?id=${x.id}">${x.titulo}</a>`).join(', ')}</div>`:''}`;lista.appendChild(li)});const map=L.map('mapa',{scrollWheelZoom:false});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap',maxZoom:17}).addTo(map);const pontos=obra.lugares.map(l=>[l.lat,l.lon]);obra.lugares.forEach(l=>{const c=TIPOS_LUGAR[l.tipo]||TIPOS_LUGAR.mencionado,z=CERTEZAS[l.certeza]||CERTEZAS.ilustrativo;L.circleMarker([l.lat,l.lon],{radius:8,color:c.cor,weight:2,dashArray:z.tracejado?'3,3':null,fillColor:'#f1ebdd',fillOpacity:1}).addTo(map).bindPopup(`<strong>${l.nome}</strong><br>${c.rotulo} · ${z.rotulo}<br>${l.descricao}`)});if(pontos.length>1)map.fitBounds(pontos,{padding:[30,30]});else map.setView(pontos[0],7)}
if(!corpus)return;
const unidadeLabel=estrutura.capitulos_auditados?'capítulos auditados':'unidades auditadas',posicao=x=>x.capitulo??x.unidade??0,chip=x=>x.unidade_label||x.capitulo_label||(x.capitulo?`Cap. ${x.capitulo}`:`Unid. ${x.unidade}`);
const sec=document.createElement('section');sec.className='corpus-profundo obra-secao obra-secao-larga';sec.innerHTML=`<div class="section-heading"><div><div class="eyebrow">Pesquisa auditável</div><h2>Corpus profundo da obra</h2></div><p><strong>${String(corpus.status||'').replaceAll('_',' ')}</strong> · versão ${corpus.versao||'—'}</p></div><div class="corpus-grade"><div class="corpus-card"><strong>${mencoes.length}</strong><span>ocorrências verificadas</span></div><div class="corpus-card"><strong>${entidades.length}</strong><span>entidades distintas</span></div><div class="corpus-card"><strong>${unidades.length}</strong><span>${unidadeLabel}</span></div><div class="corpus-card"><strong>${personagens.length}</strong><span>personagens estruturados</span></div><div class="corpus-card"><strong>${eventos.length}</strong><span>eventos estruturados</span></div><div class="corpus-card"><strong>${percursos.length}</strong><span>percursos validados</span></div></div>`;
if(personagens.length)sec.insertAdjacentHTML('beforeend',`<div class="corpus-bloco"><h3>Personagens estruturados</h3><div class="personagens-grade">${personagens.map(p=>`<article class="mini-card"><strong>${p.nome}</strong><span>${String(p.papel||'').replaceAll('-',' ')}</span></article>`).join('')}</div></div>`);
if(eventos.length)sec.insertAdjacentHTML('beforeend',`<div class="corpus-bloco"><h3>Eventos estruturados</h3><ol class="eventos-lista">${eventos.map(ev=>`<li><span class="capitulo-chip">${chip(ev)}</span><strong>${ev.titulo}</strong><span>${(ev.place_mentions||[]).length} ocorrência${(ev.place_mentions||[]).length===1?'':'s'} espacial${(ev.place_mentions||[]).length===1?'':'is'} vinculada${(ev.place_mentions||[]).length===1?'':'s'}</span></li>`).join('')}</ol></div>`);
if(mencoes.length){const ordenadas=[...mencoes].sort((a,b)=>posicao(a)-posicao(b)||String(a.canonical_name||'').localeCompare(String(b.canonical_name||''),'pt-BR'));sec.insertAdjacentHTML('beforeend',`<div class="corpus-bloco"><div class="section-heading"><div><h3>Ocorrências geográficas confirmadas no texto</h3></div><p>Identidade textual, geocodificação e rota permanecem camadas separadas.</p></div><ol class="mencoes-verificadas">${ordenadas.map(m=>{const tipo=(TIPOS_LUGAR[m.tipo]||TIPOS_LUGAR.mencionado).rotulo,certeza=(CERTEZAS[m.certeza]||CERTEZAS.ilustrativo).rotulo;return `<li><div class="mencao-topo"><span class="capitulo-chip">${chip(m)}</span><strong>${m.canonical_name}</strong></div><div class="mencao-meta">${tipo} · ${m.escala} · ${certeza}</div><p class="mencao-funcao">${m.funcao}</p>${m.evidencia&&m.evidencia.url?`<a href="${m.evidencia.url}" target="_blank" rel="noopener">Conferir evidência textual</a>`:''}</li>`}).join('')}</ol></div>`)}
if(corpus.edicao)sec.insertAdjacentHTML('beforeend',`<div class="corpus-bloco fonte-base"><h3>Edição-base</h3><p><strong>${corpus.edicao.titulo}</strong> · ${corpus.edicao.cidade}, ${corpus.edicao.editora}, ${corpus.edicao.ano}.</p>${corpus.edicao.url?`<a href="${corpus.edicao.url}" target="_blank" rel="noopener">Abrir fonte textual adotada</a>`:''}</div>`);
corpo.appendChild(sec);
})();
