(function(){
  const filtro=document.getElementById('timeline-movimento'),lista=document.getElementById('timeline-list'),summary=document.getElementById('timeline-summary'),count=document.getElementById('timeline-count');if(!filtro||!lista)return;
  const STORE='tl:timeline:filtro';
  const movimentos=[...new Set(OBRAS.map(o=>o.movimento))].sort((a,b)=>a.localeCompare(b,'pt-BR'));movimentos.forEach(m=>{const op=document.createElement('option');op.value=m;op.textContent=m;filtro.appendChild(op)});
  try{const saved=localStorage.getItem(STORE);if(saved&&movimentos.includes(saved))filtro.value=saved}catch(_){ }
  const anos=OBRAS.map(o=>o.ano);if(summary)summary.innerHTML=`<span><strong>${OBRAS.length}</strong> obras</span><span><strong>${new Set(OBRAS.map(o=>o.autor)).size}</strong> autores</span><span><strong>${movimentos.length}</strong> movimentos</span><span><strong>${Math.min(...anos)}–${Math.max(...anos)}</strong> período do acervo</span>`;
  function render(){const dados=OBRAS.filter(o=>!filtro.value||o.movimento===filtro.value).sort((a,b)=>a.ano-b.ano||a.titulo.localeCompare(b.titulo,'pt-BR'));if(count)count.textContent=`${dados.length} ${dados.length===1?'obra':'obras'} exibida${dados.length===1?'':'s'}`;const grupos=new Map();dados.forEach(o=>{const dec=Math.floor(o.ano/10)*10;const arr=grupos.get(dec)||[];arr.push(o);grupos.set(dec,arr)});lista.innerHTML=[...grupos.entries()].map(([dec,obras])=>`<section class="timeline-decade"><div class="timeline-decade-label"><div class="eyebrow">Década</div><div class="timeline-year">${dec}</div></div><div class="timeline-items">${obras.map(o=>`<a class="timeline-card" href="obra.html?id=${encodeURIComponent(o.id)}"><span class="timeline-card__year">${o.anoLabel||o.ano}</span><span><span class="timeline-card__title">${o.titulo}</span><span class="timeline-card__meta">${o.autor}</span></span><span class="timeline-card__tag">${o.movimento}</span></a>`).join('')}</div></section>`).join('')||'<div class="empty-state">Nenhuma obra neste filtro.</div>'}
  filtro.addEventListener('change',()=>{try{if(filtro.value)localStorage.setItem(STORE,filtro.value);else localStorage.removeItem(STORE)}catch(_){ }render()});render();
})();
