import { chromium } from 'playwright-core';
const base=process.env.QA_BASE_URL||'http://127.0.0.1:4173',executablePath=process.env.CHROME_PATH||'/usr/bin/google-chrome';
const browser=await chromium.launch({headless:true,executablePath,args:['--no-sandbox','--disable-dev-shm-usage']}),failures=[];
async function run(name,fn){try{await fn();console.log(`PASS ${name}`)}catch(error){failures.push(`${name}: ${error.message}`);console.error(`FAIL ${name}: ${error.stack||error.message}`)}}
function assert(c,m){if(!c)throw new Error(m)}
await run('home sem erro e responsiva',async()=>{const p=await browser.newPage({viewport:{width:1440,height:900}}),e=[];p.on('pageerror',x=>e.push(x.message));const r=await p.goto(`${base}/index.html`,{waitUntil:'networkidle'});assert(r?.ok(),'home HTTP inválida');assert((await p.locator('h1').first().textContent())?.trim(),'home sem h1');assert(!e.length,`erros JS: ${e.join(' | ')}`);await p.close()});
await run('Biblioteca editorial filtra movimentos',async()=>{const p=await browser.newPage({viewport:{width:1440,height:900}});await p.goto(`${base}/biblioteca.html`,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.querySelectorAll('#lista-obras .book-object').length>0,{timeout:20000});const n=await p.locator('#lista-obras .book-object').count();assert(n>=10,`coleção pequena: ${n}`);const s=p.locator('#filtro-movimento'),v=await s.locator('option').nth(1).getAttribute('value');await s.selectOption(v);await p.waitForTimeout(120);assert(await p.locator('#lista-obras .book-object').count()>0,'filtro zerou coleção');await p.close()});
await run('dossiê museológico mantém lazy loading único',async()=>{const p=await browser.newPage({viewport:{width:1280,height:900}}),req=[],e=[];p.on('request',r=>{const u=new URL(r.url());if(u.pathname.includes('/js/corpus/'))req.push(u.pathname)});p.on('pageerror',x=>e.push(x.message));await p.goto(`${base}/obra.html?id=o-cortico`,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.querySelector('.corpus-profundo'),{timeout:15000});assert((await p.locator('#titulo-obra').textContent())?.trim()==='O Cortiço','obra inesperada');assert(await p.locator('.work-cover-object').count()===1,'objeto-livro ausente');assert(await p.locator('#obra-facts .work-fact').count()>=4,'ficha incompleta');const loaded=await p.evaluate(()=>Object.keys(window.CORPUS_PROFUNDO||{}));assert(loaded.length===1&&loaded[0]==='o-cortico',`corpora indevidos: ${loaded.join(', ')}`);assert([...new Set(req)].length===1,'lazy loading deixou de ser único');assert(!e.length,`erros JS: ${e.join(' | ')}`);await p.close()});
await run('Atlas Experience carrega e abre dossiê',async()=>{const p=await browser.newPage({viewport:{width:1440,height:900}});await p.goto(`${base}/atlas.html`,{waitUntil:'domcontentloaded'});const expected=await p.evaluate(()=>Object.keys(window.CORPUS_REGISTRY||{}).length);await p.waitForFunction(x=>Object.keys(window.CORPUS_PROFUNDO||{}).length===x,expected,{timeout:30000});await p.waitForFunction(()=>document.querySelectorAll('#atlas-lista .atlas-lista-item').length>0,{timeout:10000});await p.locator('#atlas-lista .atlas-lista-item').first().click();await p.waitForFunction(()=>document.querySelector('.atlas-sidebar')?.classList.contains('is-detail-mode'));assert((await p.locator('#atlas-detalhe h2').textContent())?.trim(),'dossiê sem lugar');await p.close()});
await run('Autores abre perfil e coleção autoral',async()=>{const p=await browser.newPage({viewport:{width:1360,height:900}}),e=[];p.on('pageerror',x=>e.push(x.message));await p.goto(`${base}/autores.html`,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.querySelectorAll('.author-object').length>0,{timeout:20000});assert(await p.locator('.author-monogram').count()>0,'monogramas ausentes');const href=await p.locator('.author-object').first().getAttribute('href');assert(href?.includes('autor.html?nome='),'perfil sem link');await p.goto(new URL(href,base).href,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.querySelectorAll('#autor-obras .book-object').length>0,{timeout:20000});assert((await p.locator('#autor-nome').textContent())?.trim(),'perfil sem nome');assert(await p.locator('#autor-meta .profile-stat').count()>=3,'perfil sem ficha');assert(!e.length,`erros JS: ${e.join(' | ')}`);await p.close()});
await run('Linha do Tempo funciona como crônica filtrável',async()=>{const p=await browser.newPage({viewport:{width:1360,height:900}});await p.goto(`${base}/linha-do-tempo.html`,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.querySelectorAll('.timeline-card').length>0,{timeout:10000});assert(await p.locator('.chronicle-shell').count()===1,'shell de crônica ausente');const s=p.locator('#timeline-movimento'),v=await s.locator('option').nth(1).getAttribute('value');await s.selectOption(v);await p.waitForTimeout(120);assert(await p.locator('.timeline-card').count()>0,'filtro da cronologia sem resultados');await p.close()});
await run('Sobre expõe manifesto e método',async()=>{const p=await browser.newPage({viewport:{width:1280,height:850}});await p.goto(`${base}/sobre.html`,{waitUntil:'domcontentloaded'});assert(await p.locator('.manifesto-quote').count()===1,'manifesto ausente');assert(await p.locator('.method-ledger article').count()===3,'três eixos metodológicos ausentes');assert(await p.locator('.method-section').count()>=3,'seções metodológicas insuficientes');await p.close()});
await run('viewport móvel sem overflow estrutural',async()=>{for(const url of ['/index.html','/obra.html?id=memorias-postumas','/biblioteca.html','/atlas.html','/autores.html','/autor.html?nome=Machado%20de%20Assis','/linha-do-tempo.html','/sobre.html']){const p=await browser.newPage({viewport:{width:390,height:844},isMobile:true});await p.goto(base+url,{waitUntil:'domcontentloaded'});await p.waitForTimeout(url.includes('atlas')?1600:900);const d=await p.evaluate(()=>({w:innerWidth,s:document.documentElement.scrollWidth}));assert(d.s<=d.w+2,`${url}: overflow ${d.s}>${d.w}`);await p.close()}});
await run('navegação por teclado alcança link',async()=>{const p=await browser.newPage({viewport:{width:1280,height:800}});await p.goto(`${base}/index.html`,{waitUntil:'domcontentloaded'});let ok=false;for(let i=0;i<8;i++){await p.keyboard.press('Tab');if(await p.evaluate(()=>document.activeElement?.tagName)==='A'){ok=true;break}}assert(ok,'Tab não alcançou link');await p.close()});
await browser.close();if(failures.length){console.error(`\nBrowser QA: ${failures.length} falha(s)\n- ${failures.join('\n- ')}`);process.exit(1)}console.log('Browser QA OK: portal editorial completo, mobile e teclado.');